### ISSUE TITLE
issue-3: Implement Feed Component

### ISSUE THREAD

**Issue by gialynguyen** [gialynguyen/vcteam-homepage#5]
**0. Library**: momentjs

**1. File Dir**: 
	
        - /src/components/Feed: root src
        - /src/components/Feed/index.tsx
        - /src/components/Feed/feed.component.tsx
        - /src/components/Feed/__tests__
        - /src/component/Feed/styles
        - /src/component/Feed/interface.ts

**2. Todo**:
  
     - Implement Component;
     - Import to container: /src/pages/home/containers/feed.container.tsx
  
  **3. Model**:
	
		- Feed Model: (define interface FeedProps in /src/component/Feed/interface.ts):
			FeedProps {
				title: string;
				tags: {
					_id: string,
					name: string,
				}[];
				createdAt: string;
				createdBy: {
					_id: string;
					displayName: string;
				}
				descr: string;
				decsrImageUrl: string;
			}

**Comment by gialynguyen** [comment]
nên phân tách task ra, không nên 1 task phải bao trùm quá nhiều thứ:
- em code component Feed thì tại sao em lại đùng đến những thằng root khác như :
 /src/styles, /src/styles/Base ,/src/styles/Base/mixin.scss, /src/styles/Base/variable.scss, 
/src/styles/Components;
=> Giải thích cho anh từng thằng em thêm vào để làm gì

**Comment by gialynguyen** [comment]
Nên xem lại issue 1 của anh để xem lại câu trúc của project

**Comment by gialynguyen** [comment]
- /src/data: root
   - src/data/mockupData.ts
=> Những cái này ko cần thêm vào project, chỉ demo bằng cách thêm cứng vào props khi truyền vào thôi

**Comment by gialynguyen** [comment]
- Component càng ko phụ thuộc thì càng tốt nhan cả logic code và cả styles nữa. CÒn những thứ mix, hay variable kia thì cũng ko cần; Đó phạm trù của 1 task khác, khi refactor sau khi xong 1 minestone ( không như 1 page hoàn chỉnh vậy đó), lúc đó mình mới bắt đầu optimize, rút gọn code, đưa ra những thứ xài chung ra.
=> Code cho xong đã rồi refactor; Nên những thứ như:
  - /src/styles: root
    - /src/styles/Base
    - /src/styles/Base/mixin.scss
    - /src/styles/Base/variable.scss
    - /src/styles/Components
là không cần thiết trong task này

**Comment by tunganh252** [comment]
* Em định viết lại phần layout chung á anh, nên em tính tạo thêm 1 folder về styles để thêm các css dùng chung và apply cho toàn bộ
* src/styles/Base: em định thêm những thông số css dùng chung như font-size, font chữ, các biến mixin dùng lại như margin hay padding dùng chung 1 kiểu
* src/styles/Components: em có xem qua giao diện thì có 1 vài css em thấy có thể dùng lại được nên định quăng vào trong folder này: vd button..
* src/data thì không thêm cũng được anh

**Comment by gialynguyen** [comment]
> Em định viết lại phần layout chung á anh, nên em tính tạo thêm 1 folder về styles để thêm các css dùng chung và apply cho toàn bộ
=> xem lại cái anh nói trên, chưa tới lúc đưa ra nhưng thứ chung ( chưa tới lúc refactor code).
> src/styles/Base: em định thêm những thông số css dùng chung như font-size, font chữ, các biến mixin dùng lại như margin hay padding dùng chung 1 kiểu
=> cài này viết trong file index.scss.

> src/styles/Components: em có xem qua giao diện thì có 1 vài css em thấy có thể dùng lại được nên định quăng vào trong folder này: vd button..
=> cài này sai, đã là component thì độc lập, ko có chung gì hết 
> src/data thì không thêm cũng được anh
=> Data hay mocking gì đó ko thêm vào, làm loạn project, chỉ cần thêm cứng vào props khi truyền vào là đc rồi

**Comment by gialynguyen** [comment]
@tunganh252 xem qua comment của anh, nếu chưa ok thì có thể phát biểu nhan. OK xong hết rồi thì cập nhật issue và làm nhan

**Comment by tunganh252** [comment]
> @tunganh252 xem qua comment của anh, nếu chưa ok thì có thể phát biểu nhan. OK xong hết rồi thì cập nhật issue và làm nhan

@gialynguyen ok anh, vậy chắc em sẽ theo hướng code trước rồi refactor sau

**Comment by gialynguyen** [comment]
@tunganh252 Anh muốn em chủ động đưa ý kiến vậy đó. Để biết em đang hiểu sai cái gì, anh sẽ sửa, và nhất là tập cho em tính làm việc phải chủ động và bình đẳng với nhau. Cập nhật issue nhan em, có ý tưởng mới thì cứ update issue, rồi kêu anh review nhan. Fighting
